#ifndef HHM_DESKTOP_APP_H
#define HHM_DESKTOP_APP_H

/* Generated by cbindgen. Update src/ffi.rs, then run `just ffi-generate`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Major/minor ABI version encoded as `major << 16 | minor`.
#define HHM_DESKTOP_ABI_VERSION (1 << 16)

enum HhmDesktopStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  HhmDesktopStatus_Ok = 0,
  HhmDesktopStatus_NullPointer = 1,
  HhmDesktopStatus_InvalidValue = 2,
  HhmDesktopStatus_LockFailed = 3,
  HhmDesktopStatus_SerializationFailed = 4,
  HhmDesktopStatus_PanicContained = 255,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum HhmDesktopStatus HhmDesktopStatus;
#else
typedef int32_t HhmDesktopStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

typedef struct HhmDesktopHandle HhmDesktopHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t hhm_desktop_abi_version(void);

struct HhmDesktopHandle *hhm_desktop_handle_new(void);

// Releases a handle returned by [`hhm_desktop_handle_new`].
//
// # Safety
//
// `handle` must be null or a live pointer returned by this library. A live
// handle must be released exactly once and must not be used concurrently while
// this function runs.
void hhm_desktop_handle_free(struct HhmDesktopHandle *handle);

// Updates the display-only authentication outcome.
//
// Accepted values are 0 anonymous, 1 unauthenticated, 2 degraded, and 3
// authenticated. This state is never itself an authorization grant.
//
// # Safety
//
// `handle` must be a live pointer returned by this library for the duration of
// the call, or null.
HhmDesktopStatus hhm_desktop_set_auth_state(struct HhmDesktopHandle *handle, int32_t value);

// Updates the product-authorization outcome returned by HHM's backend.
//
// Accepted values are 0 unknown, 1 denied, and 2 allowed.
//
// # Safety
//
// `handle` must be a live pointer returned by this library for the duration of
// the call, or null.
HhmDesktopStatus hhm_desktop_set_product_access(struct HhmDesktopHandle *handle, int32_t value);

// Updates the opt-in proximity hint.
//
// Accepted values are 0 unknown, 1 outside range, and 2 nearby. Proximity is
// never accepted as identity proof or as evidence that a door transition
// completed.
//
// # Safety
//
// `handle` must be a live pointer returned by this library for the duration of
// the call, or null.
HhmDesktopStatus hhm_desktop_set_proximity(struct HhmDesktopHandle *handle, int32_t value);

// Updates the safe metadata for a backend-issued rotating visitor QR lease.
//
// `active` is 0 to clear or 1 to set. When set, `purpose` is 0 for sign-in or
// 1 for sign-out and `seconds_remaining` must be in 1..=60. The opaque QR
// payload is intentionally not accepted by this state/telemetry ABI.
//
// # Safety
//
// `handle` must be a live pointer returned by this library for the duration of
// the call, or null.
HhmDesktopStatus hhm_desktop_set_qr_lease(struct HhmDesktopHandle *handle,
                                          int32_t active,
                                          int32_t purpose,
                                          uint16_t seconds_remaining);

// Serializes a display-only state snapshot as UTF-8 JSON.
//
// On success, `out_json` receives an allocated NUL-terminated string that must
// be released with [`hhm_desktop_string_free`].
//
// # Safety
//
// `handle` must be a live pointer returned by this library for the duration of
// the call, or null. `out_json` must be null or point to writable storage for
// one `char *`.
HhmDesktopStatus hhm_desktop_snapshot_json(const struct HhmDesktopHandle *handle, char **out_json);

// Releases a string returned by [`hhm_desktop_snapshot_json`].
//
// # Safety
//
// `value` must be null or a live pointer returned through `out_json` by this
// library. Each live string must be released exactly once.
void hhm_desktop_string_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HHM_DESKTOP_APP_H */
